### ISSUE TITLE
[BUG]support for non-pdf format files

### ISSUE THREAD

**Issue by sha-shanks** [udeet27/SLcM-Bot#1]
## What happened?
Two of the last three files uploaded on SLcm were images.
the latest mail (sent at Jul 26, 2023, 9:23 PM) consisted only the last three PDFs rather than the images.

## Other relevant information
[bug preview](https://imgur.com/PuAEWuC)
would love to contribute on this issue!

**Comment by udeet27** [comment]
- ah yes I did see that yesterday, I had assumed initially that all documents would be of .pdf but obviously that isn't the case anymore;
- thanks for pointing it out, you're free to come up with a solution and open a PR, would be much appreciated.🙌
